### ISSUE TITLE
SharpSvn Dependency

### ISSUE THREAD

**Issue by qyte** [Zimgineering/repoBuddy#1]
You need to somehow add to the readme that:

Newer versions of SharpSvn have a dependency on the "Microsoft Visual C++ 2010 SP1 Redistributable Package".

x64 - https://www.microsoft.com/en-us/download/details.aspx?id=13523

I nearly lost it before i found out why it was not loading.

**Comment by Zimgineering** [comment]
ouch, good catch thanks!
