### ISSUE TITLE
Could you add a vpn config in some where please

### ISSUE THREAD

**Issue by HarmonyWork** [Zimgineering/repoBuddy#10]
thanks in advance, I wonder if it is possible to add something that user could fill out to enable proxy, like ‘http://localhost:7890", CN users for sure using VPN to visit github and finding this repo, but to have repoBuddy working usually need to enable global proxy for everything, normally people having some rules only proxy internet traffic for specific websites.

**Comment by Zimgineering** [comment]
Planned for v2 release which should be out in May or june, in the meantime you can try reverting the [last change](https://github.com/Zimgineering/repoBuddy/commit/6f20e9fc7984f0f0a1d27ae58f0fb0a3461b2241) by adding the following to Line 262 (after string repoPath = $@"{repoType}\{repoName}";)

    #if RB_CN
    repoUrl = repoUrl.Replace("github.com", "github.com.cnpmjs.org");
    #endif

Replace github.com.cnpmjs.org with your mirror/proxy.

Make sure that whatever url you use accepts svn, and you delete the .svn folders in the addons you're updating, you can also use this script `for /d /r . %d in (.svn) do @if exist "%d" rd /s/q "%d"` from the commandline in the root RB directory (same place as the exe) or you can run the script I just added in the repoBuddy folder (make sure it runs from the repoBuddy folder).

**Comment by HarmonyWork** [comment]
After some googing I found a solution for CN users who has VPN.
Win + R -> %APPDATA% -> \\AppData\Roaming\Subversion\servers -> edit
`
[global]
http-proxy-host = proxy_host
http-proxy-port = port_number
`
Example:
`
[global]
http-proxy-host = 127.0.0.1
http-proxy-port = 4200
`

Could you add this information somewhere for other CN players? Thanks!
