### ISSUE TITLE
After CN 5.4 patch can not use

### ISSUE THREAD

**Issue by idenpa** [Zimgineering/repoBuddy#4]
After cn 5.4 patch and rebornbuddyCN 430，repoBuddy v1.10 can not use，here is the log
https://pastebin.ubuntu.com/p/rK3MVjNdh3/
Thanks.

**Comment by Zimgineering** [comment]
Not sure what's going on here, the encoding error makes it difficult. You can try removing the below code from repoBuddyRepos.xml (jamharri closed the repo) and see if you fare any better. If the issue is 100% reproducible hit me up on discord and we'll see if we can troubleshoot quickly.
```
  <Repo>
    <Name>LizExFateBot</Name>
    <Type>BotBase</Type>
    <URL>https://github.com/jamharri/ExFateBot.git/trunk</URL>
  </Repo>
```

**Comment by idenpa** [comment]
Thanks.I will try now

**Comment by idenpa** [comment]
I find a friend to help me test the plugin,he get the same error. I think maybe it has something wrong with the CN version rb.
Every time I enable the repobuddy plugin in rb, rb will freeze about 2 minutes,then give the error log.I tyr to delete all repo in plugin setting,only left the repobuddy,it also give me the error.
And which channel or id I can find you on discord?

**Comment by Zimgineering** [comment]
I'm in the Lisbeth, Reborn Again, and Project BR servers as Zimble; near the top under House Ordos if you're in the Reborn Again server.

**Comment by Zimgineering** [comment]
Added catch for generic SvnException to warn about tortoiseSVN
