### ISSUE TITLE
Ever since repobuddy update, RB just constantly re-launches

### ISSUE THREAD

**Issue by gbtgbtgbta** [Zimgineering/repoBuddy#6]
Since today's update (https://github.com/Zimgineering/repoBuddy/commit/fc10092f02b28d747b728f665f7181aba4440403)  I get this infinate loop. 
![image](https://user-images.githubusercontent.com/95308463/144102826-21cf9cab-98a0-44e5-80fd-c3f3a01335d6.png)
![image](https://user-images.githubusercontent.com/95308463/144102772-1bb82089-b81a-4ec8-8c4d-1822380122d4.png)

Testing
- Emptied plugin and botbase folders.
- Launched RB - Working.
- Added in previous botbase folder.
- Launched RB - Working.
- Added plugin folder.
- Launched RB - Fail. Loop repeat.
- Added each plugin back 1 by 1. 
- Breaks with Repro buddy.
- Fresh install of RB, download latest repoBuddy.
- Launched RB - Fail. Loop repeat.

I've tested all other  bot bases and plugins and only have this issue during repobuddy. It was working this morning and ever since the update went out today it broke.

**Comment by Zimgineering** [comment]
Excellent report, thank you! I accidentally set the restart flag in the wrong scope, latest should fix.

**Comment by gbtgbtgbta** [comment]
Just tested - working perfectly!

Thank you kindly :)
