### ISSUE TITLE
Github Proxy hardcoded in line 264, repoBuddy.cs will cause error

### ISSUE THREAD

**Issue by hannesgao** [Zimgineering/repoBuddy#9]
https://github.com/Zimgineering/repoBuddy/blob/93629045efd24432063310843a20037fe1be2b4a/repoBuddy.cs#L264
Line 264, when RBCN user uses RBCN overseas or not with China IPs, the Github Proxy hardcoded in this line will cause error.
Looks like the URL of this proxy is not up-to-date and can not be resolved.

**Comment by Zimgineering** [comment]
Removed the proxy, please use a VPN in its place.

Thanks for the report!
